version: "2"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    container_name: blog_with_post_web_container
    env_file: ./config/.env
    depends_on:
      - db
    volumes:
      - .:/project
    command: ["./docker/sleep_before_run.sh", "15", "./docker/django/entrypoint.sh"]
    ports:
      - "8000:8000"
  db:
    image: postgres
    container_name: blog_with_post_db_container
