# Generated by Django 2.0.3 on 2018-03-07 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markupfield.fields
import model_utils.fields
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('title', models.CharField(help_text='Post Title.', max_length=256, verbose_name='Title')),
                ('body', markupfield.fields.MarkupField(help_text='Post Body.', max_length=2048, rendered_field=True, verbose_name='Body')),
                ('body_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default='markdown', max_length=30)),
                ('image', models.ImageField(blank=True, height_field=1024, help_text='Post Head Image.', null=True, upload_to=posts.models.get_blog_image_upload_path, verbose_name='Image', width_field=1024)),
                ('_body_rendered', models.TextField(editable=False)),
                ('allow_comments', models.BooleanField(default=True, help_text='Can other user add comments?', verbose_name='Allow comments')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', help_text='Post Status.', max_length=100, no_check_for_status=True, verbose_name='Status')),
                ('author', models.ForeignKey(help_text='Post Author.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-created',),
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title', 'body'], name='posts_post_title_e34876_idx'),
        ),
    ]
