# Generated by Django 2.0.3 on 2018-03-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180306_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_removed',
        ),
    ]
