# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 12:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('body', models.TextField(help_text='Comment Body.', max_length=1024, verbose_name='Comment')),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', help_text='Comment Author IP Address.', verbose_name='Ip Address')),
                ('post', models.ForeignKey(help_text='Post.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post', verbose_name='Post')),
                ('user', models.ForeignKey(help_text='Comment Author.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('-created', 'user'),
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'body', 'user', 'ip_address'], name='comments_co_post_id_535be7_idx'),
        ),
    ]
